"""empty message

Revision ID: 1661085d0402
Revises: 219ab27bf09a
Create Date: 2018-07-13 15:32:21.590982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1661085d0402'
down_revision = '219ab27bf09a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'order')
    # ### end Alembic commands ###
