"""empty message

Revision ID: 1b7eed677875
Revises: 2af37cd02c6c
Create Date: 2018-07-12 21:12:29.924201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b7eed677875'
down_revision = '2af37cd02c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tasting', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_tasting', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_tasting', type_='foreignkey')
    op.drop_column('user_tasting', 'user_id')
    # ### end Alembic commands ###
