"""empty message

Revision ID: 2af37cd02c6c
Revises: c528693c8962
Create Date: 2018-07-12 21:09:13.456288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2af37cd02c6c'
down_revision = 'c528693c8962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tasting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tasting_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tasting_id'], ['tasting.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('attendees')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendees',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('tasting_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tasting_id'], ['tasting.id'], name='attendees_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='attendees_ibfk_2'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('user_tasting')
    # ### end Alembic commands ###
