"""empty message

Revision ID: 2f88b6f0ed23
Revises: 7e3260cb4183
Create Date: 2018-06-23 00:05:39.412559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f88b6f0ed23'
down_revision = '7e3260cb4183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
