"""add tasting

Revision ID: 3d2eb5b6b28d
Revises: 2511a7eb21c5
Create Date: 2018-06-08 13:48:39.726997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d2eb5b6b28d'
down_revision = '2511a7eb21c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('review', sa.Column('tasting_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'review', 'tasting', ['tasting_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_column('review', 'tasting_id')
    op.drop_table('tasting')
    # ### end Alembic commands ###
