"""users table

Revision ID: 4ecdc679f0ac
Revises: 
Create Date: 2018-06-03 14:04:20.355066

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ecdc679f0ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_constraint('type_brand_rel', 'brand', type_='foreignkey')
    op.drop_constraint('region_brand_rel', 'brand', type_='foreignkey')
    op.create_foreign_key(None, 'brand', 'region', ['region_id'], ['id'])
    op.create_foreign_key(None, 'brand', 'type', ['type_id'], ['id'])
    op.alter_column('region', 'country_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint('country_region_rel', 'region', type_='foreignkey')
    op.create_foreign_key(None, 'region', 'country', ['country_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'region', type_='foreignkey')
    op.create_foreign_key('country_region_rel', 'region', 'country', ['country_id'], ['id'], onupdate='CASCADE')
    op.alter_column('region', 'country_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_constraint(None, 'brand', type_='foreignkey')
    op.drop_constraint(None, 'brand', type_='foreignkey')
    op.create_foreign_key('region_brand_rel', 'brand', 'region', ['region_id'], ['id'], onupdate='CASCADE')
    op.create_foreign_key('type_brand_rel', 'brand', 'type', ['type_id'], ['id'], onupdate='CASCADE')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
