"""followers

Revision ID: 5494f31f1898
Revises: 5516d78c245a
Create Date: 2018-06-03 20:03:48.717962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5494f31f1898'
down_revision = '5516d78c245a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
