"""correct tasting

Revision ID: 5fb246d29748
Revises: b0d4da5333a9
Create Date: 2018-06-11 20:00:25.793500

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5fb246d29748'
down_revision = 'b0d4da5333a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('tasting_note', sa.String(length=2000), nullable=True))
    op.drop_column('review', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('body', mysql.VARCHAR(length=140), nullable=True))
    op.drop_column('review', 'tasting_note')
    # ### end Alembic commands ###
