"""empty message

Revision ID: 7e3260cb4183
Revises: 2e557a2bc10d
Create Date: 2018-06-22 13:18:44.750787

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e3260cb4183'
down_revision = '2e557a2bc10d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('password', sa.String(length=255), server_default='', nullable=False))
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.drop_column('user', 'password')
    op.drop_column('user', 'email_confirmed_at')
    # ### end Alembic commands ###
