"""reviews table

Revision ID: 82e80be3224c
Revises: 9376abd831c4
Create Date: 2018-06-03 14:24:51.212167

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82e80be3224c'
down_revision = '9376abd831c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bottle_ibfk_3', 'bottle', type_='foreignkey')
    op.drop_column('bottle', 'type_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bottle', sa.Column('type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('bottle_ibfk_3', 'bottle', 'type', ['type_id'], ['id'])
    # ### end Alembic commands ###
