"""correct review fields

Revision ID: b0d4da5333a9
Revises: 3d2eb5b6b28d
Create Date: 2018-06-11 18:57:08.303534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0d4da5333a9'
down_revision = '3d2eb5b6b28d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('img_name', sa.String(length=140), nullable=True))
    op.add_column('review', sa.Column('notes', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'notes')
    op.drop_column('review', 'img_name')
    # ### end Alembic commands ###
