"""empty message

Revision ID: b852d7ce8726
Revises: 8ae4bb3e7c30
Create Date: 2018-06-23 10:24:55.929579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b852d7ce8726'
down_revision = '8ae4bb3e7c30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tasting_ibfk_2', 'tasting', type_='foreignkey')
    op.create_foreign_key(None, 'tasting', 'club', ['club_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasting', type_='foreignkey')
    op.create_foreign_key('tasting_ibfk_2', 'tasting', 'user', ['club_id'], ['id'])
    # ### end Alembic commands ###
