"""empty message

Revision ID: c7fb95178a8e
Revises: b894ac09f99d
Create Date: 2018-07-12 18:19:51.388556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7fb95178a8e'
down_revision = 'b894ac09f99d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tasting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tasting_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tasting_id'], ['tasting.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tasting', sa.Column('num_attendees', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasting', 'num_attendees')
    op.drop_table('user_tasting')
    # ### end Alembic commands ###
