"""remove bottle

Revision ID: e2620c271b31
Revises: 5494f31f1898
Create Date: 2018-06-04 18:09:18.456588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e2620c271b31'
down_revision = '5494f31f1898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('review_ibfk_1', 'review', type_='foreignkey')
    op.drop_table('bottle')
    op.add_column('review', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('review', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.add_column('review', sa.Column('name', sa.String(length=300), nullable=False))
    op.create_foreign_key(None, 'review', 'brand', ['brand_id'], ['id'])
    op.drop_column('review', 'bottle_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('bottle_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.create_foreign_key('review_ibfk_1', 'review', 'bottle', ['bottle_id'], ['id'])
    op.drop_column('review', 'name')
    op.drop_column('review', 'brand_id')
    op.drop_column('review', 'age')
    op.create_table('bottle',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=300), nullable=False),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('brand_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], name='bottle_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
